version: "3.9"

services:
  devopsdb:
    image: divyakoduri/dockerwebapp:db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: divyakoduri/dockerwebapp:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

volumes:
  dbdata:
networks:
  mynetwork:
    driver: overlay
