---
services:
  devopsdb:
    image: divyakoduri/dockerweb:db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  application:
    image: divyakoduri/dockerweb:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb

volumes:
  dbdata:
...
